In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import numpy as np
import os

In [106]:
def add(val1, val2):
    return val1+val2

def sub(val1, val2):
    return val1-val2

def mul(val1, val2):
    return val1*val2

def div(val1, val2):
    return val1/val2
    
operations = {0 : add,
           1 : sub,
           2 : mul,
           3 : div,
}

def getVal(val1, val2, op) :
    return operations[op](val1, val2)

def WriteTrainFile():
    MAX_VAL =10000
    SIZE_ARR =1000000
    FILE = "arithmetic.csv"
    COUNT_ARITH_OPS = 4
    
    val1Array = np.random.randint(1,MAX_VAL, size = SIZE_ARR)
    val2Array = np.random.randint(1,MAX_VAL, size = SIZE_ARR)
    opRandom =  np.random.randint(COUNT_ARITH_OPS, size = SIZE_ARR)
    
    print("File is " , FILE)
    if (os.path.isfile(FILE)):
        #print("Removed old " , FILE)
        os.remove(FILE) 
    
    fh = open(FILE, "w")
   
   
  

    desc = "V1,V2,Res,Op"+"\n"
    #print (desc)
    fh.write(desc)
    
    for index in range(0,SIZE_ARR):
        val = getVal(val1Array[index], val2Array[index], opRandom[index])
        line = str(val1Array[index]) + "," + str(val2Array[index]) + "," + str(val) + "," + str(opRandom[index]) +"\n"
        #print (line)
        fh.write(line)
    
    fh.close()
    
WriteTrainFile()
print("train file written")

File is  arithmetic.csv
train file written


In [107]:
arith = pd.read_csv("arithmetic.csv")

In [108]:
arith.head()

V1    V2           Res  Op
0  5214   170  8.863800e+05   2
1  2685  9027 -6.342000e+03   1
2  4453  1139  3.909570e+00   3
3  5476  2854  1.562850e+07   2
4  6585  9268  1.585300e+04   0

In [109]:
X = arith[['V1','V2','Res']]
print(X.head())
Y = arith ['Op']
print(Y.head())

     V1    V2           Res
0  5214   170  8.863800e+05
1  2685  9027 -6.342000e+03
2  4453  1139  3.909570e+00
3  5476  2854  1.562850e+07
4  6585  9268  1.585300e+04
0    2
1    1
2    3
3    2
4    0
Name: Op, dtype: int64


In [110]:
from sklearn.cross_validation import train_test_split

In [111]:
X_train, X_test, Y_train, Y_test = train_test_split(  X, Y, test_size=0.3, random_state=42)

In [93]:
import tensorflow.contrib.learn as learn

In [112]:
feature_columns1 = [tf.contrib.layers.real_valued_column("", dimension=3)]
classifier = learn.DNNClassifier(hidden_units=[10, 20, 10], n_classes=4, feature_columns=feature_columns1)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000025D92952240>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': 'C:\\Users\\OmSai\\AppData\\Local\\Temp\\tmpmt66_khb'}


In [113]:
classifier.fit(X_train,Y_train,steps=1000, batch_size=10000)

Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scal

DNNClassifier(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x0000025D92952E80>, 'hidden_units': [10, 20, 10], 'feature_columns': (_RealValuedColumn(column_name='', dimension=3, default_value=None, dtype=tf.float32, normalizer=None),), 'optimizer': None, 'activation_fn': <function relu at 0x0000025D88B1E6A8>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

In [114]:
predictionOps = list(classifier.predict(X_test, as_iterable=True))

Instructions for updating:
Please switch to predict_classes, or set `outputs` argument.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
INFO:tensorflow:Restoring parameters from C:\Users\OmSai\AppData\Local\Temp\tmpmt66_khb\model.ckpt-1000


In [115]:
print (X_test.head())
print(predictionOps)

          V1    V2           Res
987231  2671  8002  10673.000000
79954   9248  3438  12686.000000
567130  3339  3646   6985.000000
500891  2711  5155  -2444.000000
55399   2348   186     12.623656
[0, 0, 0, 1, 3, 2, 2, 2, 1, 0, 2, 2, 3, 2, 3, 0, 3, 1, 1, 2, 0, 2, 0, 2, 3, 0, 2, 2, 3, 1, 3, 1, 3, 1, 1, 0, 1, 0, 0, 0, 1, 2, 3, 1, 3, 2, 0, 3, 1, 1, 3, 0, 0, 0, 2, 3, 0, 3, 2, 1, 2, 3, 3, 0, 3, 3, 1, 0, 1, 2, 3, 2, 1, 0, 0, 2, 1, 1, 0, 1, 1, 2, 1, 2, 0, 2, 1, 0, 0, 3, 1, 0, 3, 2, 0, 3, 3, 3, 1, 3, 1, 3, 3, 3, 0, 0, 2, 0, 3, 1, 2, 2, 1, 3, 2, 2, 0, 2, 0, 3, 3, 3, 3, 2, 2, 1, 2, 2, 3, 3, 0, 0, 2, 2, 2, 2, 3, 3, 1, 2, 1, 1, 1, 3, 1, 1, 0, 3, 0, 2, 2, 3, 2, 1, 1, 0, 1, 0, 3, 0, 1, 3, 1, 3, 0, 3, 3, 1, 1, 2, 0, 2, 3, 0, 2, 3, 0, 2, 2, 3, 2, 0, 1, 3, 2, 3, 2, 3, 1, 2, 2, 1, 3, 1, 0, 2, 3, 2, 2, 0, 2, 3, 1, 1, 0, 1, 3, 1, 0, 3, 3, 0, 3, 0, 0, 3, 3, 3, 3, 3, 3, 0, 1, 2, 0, 2, 3, 2, 2, 2, 2, 1, 1, 1, 3, 1, 2, 0, 3, 2, 0, 2, 1, 3, 0, 3, 2, 3, 3, 3, 0, 0, 1, 3, 3, 0, 0, 1, 0, 1, 2, 2, 1, 3, 3, 3, 3, 

In [84]:
from sklearn.metrics import classification_report,confusion_matrix

In [116]:
print (classification_report(Y_test,predictionOps))
print(confusion_matrix(Y_test,predictionOps))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00     75024
          1       1.00      0.99      0.99     75029
          2       1.00      1.00      1.00     75181
          3       0.99      1.00      0.99     74766

avg / total       1.00      1.00      1.00    300000

[[74950    74     0     0]
 [   36 74302     0   691]
 [   19     9 75153     0]
 [    0    82     0 74684]]
